var dir_07c7b06f5dd7d1513dc7d4081673a960 =
[
    [ "ntp_client", "dir_f5910b02c33f121c56d84798d1ea4304.html", "dir_f5910b02c33f121c56d84798d1ea4304" ],
    [ "astronomy_conversions.hpp", "astronomy__conversions_8hpp.html", "astronomy__conversions_8hpp" ],
    [ "config.hpp", "config_8hpp.html", null ],
    [ "constants.hpp", "constants_8hpp.html", "constants_8hpp" ],
    [ "CpuTickTimer.hpp", "CpuTickTimer_8hpp.html", null ],
    [ "date_conversions.hpp", "date__conversions_8hpp.html", "date__conversions_8hpp" ],
    [ "date_struct.hpp", "date__struct_8hpp.html", "date__struct_8hpp" ],
    [ "date_time_conversions.hpp", "date__time__conversions_8hpp.html", "date__time__conversions_8hpp" ],
    [ "date_time_struct.hpp", "date__time__struct_8hpp.html", "date__time__struct_8hpp" ],
    [ "DeadlineTimer.hpp", "DeadlineTimer_8hpp.html", "DeadlineTimer_8hpp" ],
    [ "ElapsedTimer.hpp", "ElapsedTimer_8hpp.html", "ElapsedTimer_8hpp" ],
    [ "enums.hpp", "enums_8hpp.html", "enums_8hpp" ],
    [ "initialization.hpp", "initialization_8hpp.html", "initialization_8hpp" ],
    [ "MoonPhase.hpp", "MoonPhase_8hpp.html", "MoonPhase_8hpp" ],
    [ "ntp_client.hpp", "ntp__client_8hpp.html", "ntp__client_8hpp" ],
    [ "ole_automation_conversions.hpp", "ole__automation__conversions_8hpp.html", "ole__automation__conversions_8hpp" ],
    [ "time_conversion_aliases.hpp", "time__conversion__aliases_8hpp.html", "time__conversion__aliases_8hpp" ],
    [ "time_conversions.hpp", "time__conversions_8hpp.html", null ],
    [ "time_formatting.hpp", "time__formatting_8hpp.html", "time__formatting_8hpp" ],
    [ "time_parser.hpp", "time__parser_8hpp.html", "time__parser_8hpp" ],
    [ "time_struct.hpp", "time__struct_8hpp.html", "time__struct_8hpp" ],
    [ "time_unit_conversions.hpp", "time__unit__conversions_8hpp.html", "time__unit__conversions_8hpp" ],
    [ "time_utils.hpp", "time__utils_8hpp.html", "time__utils_8hpp" ],
    [ "time_zone_conversions.hpp", "time__zone__conversions_8hpp.html", "time__zone__conversions_8hpp" ],
    [ "time_zone_offset.hpp", "time__zone__offset_8hpp.html", "time__zone__offset_8hpp" ],
    [ "time_zone_offset_conversions.hpp", "time__zone__offset__conversions_8hpp.html", "time__zone__offset__conversions_8hpp" ],
    [ "time_zone_struct.hpp", "time__zone__struct_8hpp.html", "time__zone__struct_8hpp" ],
    [ "TimerScheduler.hpp", "TimerScheduler_8hpp.html", "TimerScheduler_8hpp" ],
    [ "types.hpp", "types_8hpp.html", "types_8hpp" ],
    [ "unix_time_conversions.hpp", "unix__time__conversions_8hpp.html", "unix__time__conversions_8hpp" ],
    [ "validation.hpp", "validation_8hpp.html", "validation_8hpp" ],
    [ "workday_conversions.hpp", "workday__conversions_8hpp.html", "workday__conversions_8hpp" ]
];