var hierarchy =
[
    [ "time_shield::BasicPoolRunner< PoolT >", "classtime__shield_1_1BasicPoolRunner.html", null ],
    [ "time_shield::CpuTickTimer", "classtime__shield_1_1CpuTickTimer.html", null ],
    [ "time_shield::DateStruct", "structtime__shield_1_1DateStruct.html", null ],
    [ "time_shield::DateTime", "classtime__shield_1_1DateTime.html", null ],
    [ "time_shield::DateTimeStruct", "structtime__shield_1_1DateTimeStruct.html", null ],
    [ "time_shield::DeadlineTimer", "classtime__shield_1_1DeadlineTimer.html", null ],
    [ "time_shield::detail::DueTimer", "structtime__shield_1_1detail_1_1DueTimer.html", null ],
    [ "time_shield::ElapsedTimer", "classtime__shield_1_1ElapsedTimer.html", null ],
    [ "time_shield::detail::FakeNtpRunner", "classtime__shield_1_1detail_1_1FakeNtpRunner.html", null ],
    [ "time_shield::IsoWeekDateStruct", "structtime__shield_1_1IsoWeekDateStruct.html", null ],
    [ "time_shield::detail::IUdpTransport", "classtime__shield_1_1detail_1_1IUdpTransport.html", [
      [ "time_shield::detail::UdpTransportPosix", "classtime__shield_1_1detail_1_1UdpTransportPosix.html", null ],
      [ "time_shield::detail::UdpTransportWin", "classtime__shield_1_1detail_1_1UdpTransportWin.html", null ]
    ] ],
    [ "time_shield::astronomy::MoonPhase", "classtime__shield_1_1astronomy_1_1MoonPhase.html", null ],
    [ "time_shield::astronomy::MoonPhaseResult", "structtime__shield_1_1astronomy_1_1MoonPhaseResult.html", null ],
    [ "time_shield::MoonPhaseSineCosine", "structtime__shield_1_1MoonPhaseSineCosine.html", null ],
    [ "time_shield::astronomy::MoonQuarterInstants", "structtime__shield_1_1astronomy_1_1MoonQuarterInstants.html", null ],
    [ "time_shield::NtpClient", "classtime__shield_1_1NtpClient.html", null ],
    [ "time_shield::detail::NtpClientCore", "classtime__shield_1_1detail_1_1NtpClientCore.html", null ],
    [ "time_shield::NtpClientPool", "classtime__shield_1_1NtpClientPool.html", null ],
    [ "time_shield::NtpClientPoolRunner", "classtime__shield_1_1NtpClientPoolRunner.html", null ],
    [ "time_shield::NtpClientPoolT< ClientT >", "classtime__shield_1_1NtpClientPoolT.html", null ],
    [ "time_shield::detail::NtpPacket", "structtime__shield_1_1detail_1_1NtpPacket.html", null ],
    [ "time_shield::NtpPoolConfig", "structtime__shield_1_1NtpPoolConfig.html", null ],
    [ "time_shield::NtpSample", "structtime__shield_1_1NtpSample.html", null ],
    [ "time_shield::NtpServerConfig", "structtime__shield_1_1NtpServerConfig.html", null ],
    [ "time_shield::NtpTimeService", "classtime__shield_1_1NtpTimeService.html", null ],
    [ "time_shield::NtpTimeServiceT< RunnerT >", "classtime__shield_1_1NtpTimeServiceT.html", null ],
    [ "time_shield::detail::RunningTimerScope", "structtime__shield_1_1detail_1_1RunningTimerScope.html", null ],
    [ "time_shield::detail::ScheduledComparator", "structtime__shield_1_1detail_1_1ScheduledComparator.html", null ],
    [ "time_shield::detail::ScheduledTimer", "structtime__shield_1_1detail_1_1ScheduledTimer.html", null ],
    [ "time_shield::NtpClientPoolT< ClientT >::ServerState", "structtime__shield_1_1NtpClientPoolT_1_1ServerState.html", null ],
    [ "time_shield::Timer", "classtime__shield_1_1Timer.html", null ],
    [ "time_shield::TimerScheduler", "classtime__shield_1_1TimerScheduler.html", null ],
    [ "time_shield::detail::TimerState", "structtime__shield_1_1detail_1_1TimerState.html", null ],
    [ "time_shield::TimeStruct", "structtime__shield_1_1TimeStruct.html", null ],
    [ "time_shield::TimeZoneStruct", "structtime__shield_1_1TimeZoneStruct.html", null ],
    [ "time_shield::detail::UdpRequest", "structtime__shield_1_1detail_1_1UdpRequest.html", null ],
    [ "time_shield::WsaGuard", "classtime__shield_1_1WsaGuard.html", null ]
];