var searchData=
[
  ['safe_20сервисов_20в_20c_2011_2014_0',['Исключение для late-teardown-safe сервисов в C++11/14',['../md_docs_2singleton-storage-guidelines-RU.html#autotoc_md99',1,'']]],
  ['safe_20services_1',['C++11/14 exception for late-teardown-safe services',['../md_docs_2singleton-storage-guidelines.html#autotoc_md110',1,'']]],
  ['service_2',['NTP client, pool, and time service',['../index.html#ntp_sec',1,'']]],
  ['service_20contract_3',['NTP Service Contract',['../md_docs_2library-integration-guidelines.html#autotoc_md86',1,'']]],
  ['service_20storage_20в_20header_20only_20c_20коде_4',['Рекомендации по хранению singleton / service storage в header-only C++ коде',['../md_docs_2singleton-storage-guidelines-RU.html',1,'']]],
  ['service_20storage_20guidelines_5',['Header-only Singleton / Service Storage Guidelines',['../md_docs_2singleton-storage-guidelines.html',1,'']]],
  ['services_6',['C++11/14 exception for late-teardown-safe services',['../md_docs_2singleton-storage-guidelines.html#autotoc_md110',1,'']]],
  ['shapes_7',['Supported Integration Shapes',['../md_docs_2library-integration-guidelines.html#autotoc_md84',1,'']]],
  ['shared_20stl_20and_20domain_20includes_8',['Shared STL and domain includes',['../md_docs_2header-implementation-guidelines.html#autotoc_md68',1,'']]],
  ['shield_9',['Why Time Shield?',['../index.html#motivation_sec',1,'']]],
  ['shield_20library_10',['Time Shield Library',['../index.html',1,'']]],
  ['singleton_20service_20storage_20в_20header_20only_20c_20коде_11',['Рекомендации по хранению singleton / service storage в header-only C++ коде',['../md_docs_2singleton-storage-guidelines-RU.html',1,'']]],
  ['singleton_20service_20storage_20guidelines_12',['Header-only Singleton / Service Storage Guidelines',['../md_docs_2singleton-storage-guidelines.html',1,'']]],
  ['standalone_20leaf_20first_20подсистема_13',['Standalone-leaf-first подсистема',['../md_docs_2header-implementation-guidelines-RU.html#autotoc_md46',1,'']]],
  ['standalone_20leaf_20first_20subsystem_14',['Standalone-leaf-first subsystem',['../md_docs_2header-implementation-guidelines.html#autotoc_md66',1,'']]],
  ['static_20libraries_15',['Multiple Static Libraries',['../md_docs_2library-integration-guidelines.html#autotoc_md85',1,'']]],
  ['stl_20и_20доменные_20include_20ы_16',['Общие STL и доменные include&apos;ы',['../md_docs_2header-implementation-guidelines-RU.html#autotoc_md48',1,'']]],
  ['stl_20and_20domain_20includes_17',['Shared STL and domain includes',['../md_docs_2header-implementation-guidelines.html#autotoc_md68',1,'']]],
  ['storage_20в_20header_20only_20c_20коде_18',['Рекомендации по хранению singleton / service storage в header-only C++ коде',['../md_docs_2singleton-storage-guidelines-RU.html',1,'']]],
  ['storage_20guidelines_19',['Header-only Singleton / Service Storage Guidelines',['../md_docs_2singleton-storage-guidelines.html',1,'']]],
  ['structures_3a_20',['Structures:',['../group__time__structures.html#autotoc_md12',1,'Included Structures:'],['../group__mql5__time__structures.html#autotoc_md28',1,'Included Structures:']]],
  ['submodule_20with_20add_5fsubdirectory_21',['Git submodule with &lt;span class=&quot;tt&quot;&gt;add_subdirectory&lt;/span&gt;',['../index.html#install_submodule',1,'']]],
  ['subsystem_22',['subsystem',['../md_docs_2header-implementation-guidelines.html#autotoc_md65',1,'Aggregate-first subsystem'],['../md_docs_2header-implementation-guidelines.html#autotoc_md66',1,'Standalone-leaf-first subsystem']]],
  ['supported_20integration_20shapes_23',['Supported Integration Shapes',['../md_docs_2library-integration-guidelines.html#autotoc_md84',1,'']]]
];
